// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package ponzi is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	Stock
*/
package ponzi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	CurrentStock *Stock   `protobuf:"bytes,1,opt,name=current_stock,json=currentStock" json:"current_stock,omitempty"`
	Stocks       []*Stock `protobuf:"bytes,2,rep,name=stocks" json:"stocks,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetCurrentStock() *Stock {
	if m != nil {
		return m.CurrentStock
	}
	return nil
}

func (m *Config) GetStocks() []*Stock {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type Stock struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *Stock) Reset()                    { *m = Stock{} }
func (m *Stock) String() string            { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()               {}
func (*Stock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Stock) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "ponzi.Config")
	proto.RegisterType((*Stock)(nil), "ponzi.Stock")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xc8, 0xcf, 0xab, 0xca, 0x54,
	0x4a, 0xe4, 0x62, 0x73, 0x06, 0x0b, 0x0b, 0x19, 0x72, 0xf1, 0x26, 0x97, 0x16, 0x15, 0xa5, 0xe6,
	0x95, 0xc4, 0x17, 0x97, 0xe4, 0x27, 0x67, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8,
	0x81, 0x15, 0xea, 0x05, 0x83, 0xc4, 0x82, 0x78, 0xa0, 0x4a, 0xc0, 0x3c, 0x21, 0x15, 0x2e, 0x36,
	0xb0, 0xd2, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0c, 0xb5, 0x50, 0x39, 0x25, 0x79, 0x2e, 0x56, 0x88,
	0x72, 0x31, 0x2e, 0xb6, 0xe2, 0xca, 0xdc, 0xa4, 0xfc, 0x1c, 0xb0, 0xd1, 0x9c, 0x41, 0x50, 0x5e,
	0x12, 0x1b, 0xd8, 0x45, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x2c, 0x0e, 0x5c, 0xa1,
	0x00, 0x00, 0x00,
}
