// Code generated by "stringer -type=PriceStyle"; DO NOT EDIT.

package chart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriceStyleUnspecified-0]
	_ = x[Bar-1]
	_ = x[Candlestick-2]
}

const _PriceStyle_name = "PriceStyleUnspecifiedBarCandlestick"

var _PriceStyle_index = [...]uint8{0, 21, 24, 35}

func (i PriceStyle) String() string {
	if i < 0 || i >= PriceStyle(len(_PriceStyle_index)-1) {
		return "PriceStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PriceStyle_name[_PriceStyle_index[i]:_PriceStyle_index[i+1]]
}
