// Code generated by "stringer -type=Style"; DO NOT EDIT.

package chart

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleUnspecified-0]
	_ = x[StyleBar-1]
	_ = x[StyleCandlestick-2]
}

const _Style_name = "StyleUnspecifiedStyleBarStyleCandlestick"

var _Style_index = [...]uint8{0, 16, 24, 40}

func (i Style) String() string {
	if i < 0 || i >= Style(len(_Style_index)-1) {
		return "Style(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Style_name[_Style_index[i]:_Style_index[i+1]]
}
