// Code generated by "stringer -type=controllerSignal"; DO NOT EDIT.

package controller

import "strconv"

const _controllerSignal_name = "signalUnspecifiedsignalRefreshCurrentStock"

var _controllerSignal_index = [...]uint8{0, 17, 42}

func (i controllerSignal) String() string {
	if i < 0 || i >= controllerSignal(len(_controllerSignal_index)-1) {
		return "controllerSignal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _controllerSignal_name[_controllerSignal_index[i]:_controllerSignal_index[i+1]]
}
