// Code generated by "stringer -type=signal"; DO NOT EDIT.

package controller

import "strconv"

const _signal_name = "signalUnspecifiedrefreshAllStocks"

var _signal_index = [...]uint8{0, 17, 33}

func (i signal) String() string {
	if i < 0 || i >= signal(len(_signal_index)-1) {
		return "signal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _signal_name[_signal_index[i]:_signal_index[i+1]]
}
