// Code generated by "esc -o bindata.go -pkg gfx -include .*(frag|ply|vert) -modtime 1337 -private data"; DO NOT EDIT.

package gfx

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/data/shader.frag": {
		local:   "data/shader.frag",
		size:    430,
		modtime: 1337,
		compressed: `
H4sIAAAAAAAC/3yPwU7DMAyGz/FTWOKSShMaZQOJaqftRULqQUQSIycpILR3R1m7Do2Jm+18n/P7ZiBJ
jiOu1ku0LATgzReXrD1bk+vLBtcNluj2LAFdzBi4p+4K9nDGkgnvnqTdYabPXOQq/3jmB7L3R3TLnqUD
cLHOVmjHfmzbimyZpe8AuOQR2Yt5OWkDux6DcVHXqsFvUOnDZfuKuqY+DqxJhMsnUGo2cXP6SKlnIfPW
wcTdXXLTPe1OT9ViDtX81dtLvSbW86GLf9fdyu+N6gCHnwAAAP//XHeLfq4BAAA=
`,
	},

	"/data/shader.vert": {
		local:   "data/shader.vert",
		size:    401,
		modtime: 1337,
		compressed: `
H4sIAAAAAAAC/2yQTU/EIBCGz+VXvImX7Z7WiqdNT3s28WC8GkLRjAGmobTWGP+7oR+hMdxg5nmYd7ib
TBiIPeTjBZqDEcKqbx7jybJWMXVaXGqMnt45ODgVJfrAn0an5iuZrycVA83Xgnf/z3PcGbvjBb6pQR6T
0RI9D5SqpWcfMkb+xpZDiZI71YD8i5lvzKG7CsFjXF29mtu9QczMxNTBKfKndKrxI6oP+/a8ZUJb/AGc
jwvifNihWmahzXmrfdpSzPF+/wIAAP//bRPYZJEBAAA=
`,
	},

	"/data/squarePlane.ply": {
		local:   "data/squarePlane.ply",
		size:    644,
		modtime: 1337,
		compressed: `
H4sIAAAAAAAC/5yPUU7DMBBE/32K+StINHJSJAifcAFuUDn2hlpy7LC2ScPpkRLUlgQkVP94NLvztNO7
UbSBO5WgorYWZSGFDl1HPuGFSSUyaEY8O/KGGFXx8IibmBvIW2wxDEPRzKMi8NsdYsisCa119IRNfM+K
6dUpT/PaRpCjif1BnOiIe9Fz6InTiNYFlXBcGuPS+FwafpXxq5BfpeLSSKfbWqUJ1XnubEzI+qAY2Z5u
31tvrKYoyJv9gZQhFtuykNPDWcm/xc+d8kKIq0F1Xde/gq7lzOKi2hq0/V+1b9IOEiWq6a+wE18BAAD/
/+U+DeaEAgAA
`,
	},

	"/data/textPlane.ply": {
		local:   "data/textPlane.ply",
		size:    641,
		modtime: 1337,
		compressed: `
H4sIAAAAAAAC/5yP4U6EMBCE//cp5t9pIqTlTBR/6gv4BpdSFq9JaUm7CPj0JtwFT9Born86+XZnMtu5
STQhtpqhk7EWKpfChLYlz3iJpJlqVBOeHfmaIor84RE3qa8gb5FhGIa8Oo3yEN/ukEIfDaGxjp6wYxr5
1WlPp6WdIEdz8jtFphH3oouho8gTGhc0Y1yDaQ0+1sBvPH5j8htXWgNeujXaEIqvubOJ0Zujjujt0v1g
fW0NJUG+PhxJ1xSFzOX8sBXZFqlvRF0IoX7e+TuoLMvyQohMXpu0VDonqd9v+1+j82l7SCgU87+HEp8B
AAD//8x1IwyBAgAA
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/data": {
		isDir: true,
		local: "data",
	},
}
