// Code generated by go-bindata.
// sources:
// data/shader.frag
// data/shader.vert
// data/squarePlane.ply
// data/testTexture.png
// data/textPlane.ply
// DO NOT EDIT!

package gfx

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _shaderFrag = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x8f\xc1\x4e\xc3\x30\x0c\x86\xcf\xf1\x53\x58\xe2\x92\x4a\x13\x1a\x65\x03\x89\x6a\xa7\xed\x45\x42\xea\x41\x44\x12\x23\x27\x29\x20\xb4\x77\x47\x59\xbb\x0e\x8d\x89\x9b\xed\x7c\x9f\xf3\xfb\x66\x20\x49\x8e\x23\xae\xd6\x4b\xb4\x2c\x04\xe0\xcd\x17\x97\xac\x3d\x5b\x93\xeb\xcb\x06\xd7\x0d\x96\xe8\xf6\x2c\x01\x5d\xcc\x18\xb8\xa7\xee\x0a\xf6\x70\xc6\x92\x09\xef\x9e\xa4\xdd\x61\xa6\xcf\x5c\xe4\x2a\xff\x78\xe6\x07\xb2\xf7\x47\x74\xcb\x9e\xa5\x03\x70\xb1\xce\x56\x68\xc7\x7e\x6c\xdb\x8a\x6c\x99\xa5\xef\x00\xb8\xe4\x11\xd9\x8b\x79\x39\x69\x03\xbb\x1e\x83\x71\x51\xd7\xaa\xc1\x6f\x50\xe9\xc3\x65\xfb\x8a\xba\xa6\x3e\x0e\xac\x49\x84\xcb\x27\x50\x6a\x36\x71\x73\xfa\x48\xa9\x67\x21\xf3\xd6\xc1\xc4\xdd\x5d\x72\xd3\x3d\xed\x4e\x4f\xd5\x62\x0e\xd5\xfc\xd5\xdb\x4b\xbd\x26\xd6\xf3\xa1\x8b\x7f\xd7\xdd\xca\xef\x8d\xea\x00\x87\x9f\x00\x00\x00\xff\xff\x5c\x77\x8b\x7e\xae\x01\x00\x00")

func shaderFragBytes() ([]byte, error) {
	return bindataRead(
		_shaderFrag,
		"shader.frag",
	)
}

func shaderFrag() (*asset, error) {
	bytes, err := shaderFragBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "shader.frag", size: 430, mode: os.FileMode(438), modTime: time.Unix(1507508275, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _shaderVert = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x90\x4d\x4f\xc4\x20\x10\x86\xcf\xe5\x57\xbc\x89\x97\xed\x9e\xd6\x8a\xa7\x4d\x4f\x7b\x36\xf1\x60\xbc\x1a\x42\xd1\x8c\x01\xa6\xa1\xb4\xd6\x18\xff\xbb\xa1\x1f\xa1\x31\xdc\x60\xe6\x79\x98\x77\xb8\x9b\x4c\x18\x88\x3d\xe4\xe3\x05\x9a\x83\x11\xc2\xaa\x6f\x1e\xe3\xc9\xb2\x56\x31\x75\x5a\x5c\x6a\x8c\x9e\xde\x39\x38\x38\x15\x25\xfa\xc0\x9f\x46\xa7\xe6\x2b\x99\xaf\x27\x15\x03\xcd\xd7\x82\x77\xff\xcf\x73\xdc\x19\xbb\xe3\x05\xbe\xa9\x41\x1e\x93\xd1\x12\x3d\x0f\x94\xaa\xa5\x67\x1f\x32\x46\xfe\xc6\x96\x43\x89\x92\x3b\xd5\x80\xfc\x8b\x99\x6f\xcc\xa1\xbb\x0a\xc1\x63\x5c\x5d\xbd\x9a\xdb\xbd\x41\xcc\xcc\xc4\xd4\xc1\x29\xf2\xa7\x74\xaa\xf1\x23\xaa\x0f\xfb\xf6\xbc\x65\x42\x5b\xfc\x01\x9c\x8f\x0b\xe2\x7c\xd8\xa1\x5a\x66\xa1\xcd\x79\xab\x7d\xda\x52\xcc\xf1\x7e\xff\x02\x00\x00\xff\xff\x6d\x13\xd8\x64\x91\x01\x00\x00")

func shaderVertBytes() ([]byte, error) {
	return bindataRead(
		_shaderVert,
		"shader.vert",
	)
}

func shaderVert() (*asset, error) {
	bytes, err := shaderVertBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "shader.vert", size: 401, mode: os.FileMode(438), modTime: time.Unix(1507508320, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _squareplanePly = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x8f\x51\x4e\xc3\x30\x10\x44\xff\x7d\x8a\xf9\x2b\x48\x34\x72\x52\x24\x08\x9f\x70\x01\x6e\x50\x39\xf6\x86\x5a\x72\xec\xb0\xb6\x49\xc3\xe9\x91\x12\xd4\x96\x04\x24\x54\xff\x78\x34\xbb\xf3\xb4\xd3\xbb\x51\xb4\x81\x3b\x95\xa0\xa2\xb6\x16\x65\x21\x85\x0e\x5d\x47\x3e\xe1\x85\x49\x25\x32\x68\x46\x3c\x3b\xf2\x86\x18\x55\xf1\xf0\x88\x9b\x98\x1b\xc8\x5b\x6c\x31\x0c\x43\xd1\xcc\xa3\x22\xf0\xdb\x1d\x62\xc8\xac\x09\xad\x75\xf4\x84\x4d\x7c\xcf\x8a\xe9\xd5\x29\x4f\xf3\xda\x46\x90\xa3\x89\xfd\x41\x9c\xe8\x88\x7b\xd1\x73\xe8\x89\xd3\x88\xd6\x05\x95\x70\x5c\x1a\xe3\xd2\xf8\x5c\x1a\x7e\x95\xf1\xab\x90\x5f\xa5\xe2\xd2\x48\xa7\xdb\x5a\xa5\x09\xd5\x79\xee\x6c\x4c\xc8\xfa\xa0\x18\xd9\x9e\x6e\xdf\x5b\x6f\xac\xa6\x28\xc8\x9b\xfd\x81\x94\x21\x16\xdb\xb2\x90\xd3\xc3\x59\xc9\xbf\xc5\xcf\x9d\xf2\x42\x88\xab\x41\x75\x5d\xd7\xbf\x82\xae\xe5\xcc\xe2\xa2\xda\x1a\xb4\xfd\x5f\xb5\x6f\xd2\x0e\x12\x25\xaa\xe9\xaf\xb0\x13\x5f\x01\x00\x00\xff\xff\xe5\x3e\x0d\xe6\x84\x02\x00\x00")

func squareplanePlyBytes() ([]byte, error) {
	return bindataRead(
		_squareplanePly,
		"squarePlane.ply",
	)
}

func squareplanePly() (*asset, error) {
	bytes, err := squareplanePlyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "squarePlane.ply", size: 644, mode: os.FileMode(438), modTime: time.Unix(1507500773, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _testtexturePng = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xea\x0c\xf0\x73\xe7\xe5\x92\xe2\x62\x60\x60\xe0\xf5\xf4\x70\x09\x62\x60\x60\x68\x00\x61\x0e\x36\x06\x06\x86\xc3\x76\x89\xa7\x19\x18\x18\x05\x3c\x5d\x1c\x43\x2a\x6e\xbd\xbd\x73\x90\x97\x41\x91\x83\xc1\xd1\xe4\xdb\x7d\xa3\xba\xb7\x0e\x17\x66\x72\xd9\x6c\x7a\x58\x6a\x65\xa4\xd4\x9c\xef\xab\x2c\xc0\xc0\xe4\xc0\xc0\xc1\xc0\xa8\xc0\xc0\xd2\xc0\x80\x97\xb3\x60\xf6\xd5\x87\x13\x16\xbf\x2c\xb8\xcc\x86\x2c\xdc\xba\x66\xba\xdd\xb1\xec\x70\x33\xdc\x3a\x1b\x18\x7a\x1c\x18\x6a\xde\xac\xac\x67\xca\x8f\x53\xf2\x95\x46\x56\x23\xf2\xbc\x68\x05\x2f\x01\x6b\x71\x70\x34\x56\x1f\x15\x36\x9c\x57\xb7\x91\x91\x68\xcd\xcb\x79\x65\x36\x73\xb0\x36\x5f\x7e\xf8\x81\x81\x81\x81\xc1\xd3\xd5\xcf\x65\x9d\x53\x42\x13\x20\x00\x00\xff\xff\x18\xf7\xe3\x78\x49\x01\x00\x00")

func testtexturePngBytes() ([]byte, error) {
	return bindataRead(
		_testtexturePng,
		"testTexture.png",
	)
}

func testtexturePng() (*asset, error) {
	bytes, err := testtexturePngBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "testTexture.png", size: 329, mode: os.FileMode(438), modTime: time.Unix(1504323831, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _textplanePly = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x8f\x41\x4e\xc3\x30\x14\x44\xf7\x3e\xc5\xec\x0a\x12\x8d\xe2\x14\x09\xc2\x12\x2e\xc0\x0d\x2a\xc7\xfe\xa1\x96\x1c\x3b\xb2\x7f\x48\xc2\xe9\x91\xd2\xaa\x94\xb8\x80\xf0\xc6\xa3\xf7\xff\x8c\xc7\xbd\x9b\x45\x1b\x62\xa7\x18\x2a\x69\x6b\x21\x8b\x52\xe8\xd0\x75\xe4\x19\x2f\x91\x14\x93\x41\x33\xe3\xd9\x91\x37\x14\x51\x15\x0f\x8f\xb8\x49\x43\x83\xf2\x16\x5b\x8c\xe3\x58\x34\xc7\x51\x11\xe2\xdb\x1d\x52\x18\xa2\x26\xb4\xd6\xd1\x13\x36\x4c\x13\xbf\x3a\xe5\xe9\xb8\xb4\x11\xe4\x68\x49\x7e\xa7\xc8\x34\xe1\x5e\xf4\x31\xf4\x14\x79\x46\xeb\x82\x62\x4c\x6b\x30\xaf\xc1\xc7\x1a\xf8\xcc\xe3\x33\x93\xcf\x5c\x69\x0d\xf8\xdc\xad\x55\x9a\x50\x7d\xcd\x9d\x4d\x8c\x41\x1f\x54\xc4\x60\xcf\xdd\xf7\xd6\x1b\xab\x29\x09\xf2\x66\x7f\x20\x65\x28\x8a\xb2\x28\x97\x83\x5c\x6c\x73\x24\xbf\x11\x79\x21\x84\xbc\xbe\xf3\x77\x50\x5d\xd7\xf5\x85\x10\xdb\x1f\x5e\xfb\x47\xa5\x53\x52\xee\xff\x45\x5c\x6b\x74\xfa\xda\x0e\x25\x24\xaa\xe5\xde\x41\x8a\xcf\x00\x00\x00\xff\xff\xcc\x75\x23\x0c\x81\x02\x00\x00")

func textplanePlyBytes() ([]byte, error) {
	return bindataRead(
		_textplanePly,
		"textPlane.ply",
	)
}

func textplanePly() (*asset, error) {
	bytes, err := textplanePlyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "textPlane.ply", size: 641, mode: os.FileMode(438), modTime: time.Unix(1504402834, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"shader.frag": shaderFrag,
	"shader.vert": shaderVert,
	"squarePlane.ply": squareplanePly,
	"testTexture.png": testtexturePng,
	"textPlane.ply": textplanePly,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"shader.frag": &bintree{shaderFrag, map[string]*bintree{}},
	"shader.vert": &bintree{shaderVert, map[string]*bintree{}},
	"squarePlane.ply": &bintree{squareplanePly, map[string]*bintree{}},
	"testTexture.png": &bintree{testtexturePng, map[string]*bintree{}},
	"textPlane.ply": &bintree{textplanePly, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

