// Code generated by "stringer -type=Range"; DO NOT EDIT.

package iex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RangeUnspecified-0]
	_ = x[OneDay-1]
	_ = x[TwoYears-2]
}

const _Range_name = "RangeUnspecifiedOneDayTwoYears"

var _Range_index = [...]uint8{0, 16, 22, 30}

func (i Range) String() string {
	if i < 0 || i >= Range(len(_Range_index)-1) {
		return "Range(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Range_name[_Range_index[i]:_Range_index[i+1]]
}
