// Code generated by "stringer -type=Range"; DO NOT EDIT.

package iex

import "strconv"

const _Range_name = "OneDayTwoYears"

var _Range_index = [...]uint8{0, 6, 14}

func (i Range) String() string {
	if i < 0 || i >= Range(len(_Range_index)-1) {
		return "Range(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Range_name[_Range_index[i]:_Range_index[i+1]]
}
