// Code generated by "stringer -type=Interval stock.go"; DO NOT EDIT.

package alpha

import "strconv"

const _Interval_name = "DailyWeekly"

var _Interval_index = [...]uint8{0, 5, 11}

func (i Interval) String() string {
	if i < 0 || i >= Interval(len(_Interval_index)-1) {
		return "Interval(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interval_name[_Interval_index[i]:_Interval_index[i+1]]
}
