// Code generated by "stringer -type=animationState"; DO NOT EDIT.

package view

import "strconv"

const _animationState_name = "aStoppedaRunningaFinishing"

var _animationState_index = [...]uint8{0, 8, 16, 26}

func (i animationState) String() string {
	if i < 0 || i >= animationState(len(_animationState_index)-1) {
		return "animationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _animationState_name[_animationState_index[i]:_animationState_index[i+1]]
}
