// Code generated by "stringer -type Key"; DO NOT EDIT.

package view

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUnspecified-0]
	_ = x[KeyEnter-1]
	_ = x[KeyEscape-2]
	_ = x[KeyBackspace-3]
}

const _Key_name = "KeyUnspecifiedKeyEnterKeyEscapeKeyBackspace"

var _Key_index = [...]uint8{0, 14, 22, 31, 43}

func (i Key) String() string {
	if i < 0 || i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
