// Code generated by "stringer -type ScrollDirection"; DO NOT EDIT.

package view

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScrollDirectionUnspecified-0]
	_ = x[ScrollUp-1]
	_ = x[ScrollDown-2]
}

const _ScrollDirection_name = "ScrollDirectionUnspecifiedScrollUpScrollDown"

var _ScrollDirection_index = [...]uint8{0, 26, 34, 44}

func (i ScrollDirection) String() string {
	if i < 0 || i >= ScrollDirection(len(_ScrollDirection_index)-1) {
		return "ScrollDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScrollDirection_name[_ScrollDirection_index[i]:_ScrollDirection_index[i+1]]
}
