// Code generated by "stringer -type=ZoomChange"; DO NOT EDIT.

package view

import "strconv"

const _ZoomChange_name = "ZoomChangeUnspecifiedZoomInZoomOut"

var _ZoomChange_index = [...]uint8{0, 21, 27, 34}

func (i ZoomChange) String() string {
	if i < 0 || i >= ZoomChange(len(_ZoomChange_index)-1) {
		return "ZoomChange(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoomChange_name[_ZoomChange_index[i]:_ZoomChange_index[i+1]]
}
