// Code generated by "stringer -type=AverageType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AverageTypeUnspecified-0]
	_ = x[Simple-1]
	_ = x[Exponential-2]
}

const _AverageType_name = "AverageTypeUnspecifiedSimpleExponential"

var _AverageType_index = [...]uint8{0, 22, 28, 39}

func (i AverageType) String() string {
	if i < 0 || i >= AverageType(len(_AverageType_index)-1) {
		return "AverageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AverageType_name[_AverageType_index[i]:_AverageType_index[i+1]]
}
